package com.ortodontalio.alphaesletters.common;

import net.minecraft.item.ItemStack;
import net.minecraft.util.StringIdentifiable;

import java.util.Locale;

public enum Letters implements StringIdentifiable {
    NONE,
    LETTER_1,
    LETTER_2,
    LETTER_3,
    LETTER_4,
    LETTER_5,
    LETTER_6,
    LETTER_7,
    LETTER_8,
    LETTER_9,
    LETTER_A,
    LETTER_APOSTROPHE,
    LETTER_B,
    LETTER_BOT_UP_LINE,
    LETTER_C,
    LETTER_CH,
    LETTER_CROSS,
    LETTER_CYR_AE,
    LETTER_CYR_B,
    LETTER_CYR_C,
    LETTER_CYR_CH,
    LETTER_CYR_D,
    LETTER_CYR_DZHE,
    LETTER_CYR_DZHI,
    LETTER_CYR_E,
    LETTER_CYR_EO,
    LETTER_CYR_F,
    LETTER_CYR_G,
    LETTER_CYR_GG,
    LETTER_CYR_GH,
    LETTER_CYR_HARD,
    LETTER_CYR_I,
    LETTER_CYR_II,
    LETTER_CYR_IO,
    LETTER_CYR_J,
    LETTER_CYR_JI,
    LETTER_CYR_KH,
    LETTER_CYR_L,
    LETTER_CYR_NG,
    LETTER_CYR_P,
    LETTER_CYR_RIVER,
    LETTER_CYR_SH,
    LETTER_CYR_SHCH,
    LETTER_CYR_SHKHA,
    LETTER_CYR_SOFT,
    LETTER_CYR_U,
    LETTER_CYR_UU,
    LETTER_CYR_W,
    LETTER_CYR_X,
    LETTER_CYR_Y,
    LETTER_CYR_YA,
    LETTER_CYR_YE,
    LETTER_CYR_YO,
    LETTER_CYR_YU,
    LETTER_CYR_Z,
    LETTER_CYR_ZH,
    LETTER_D,
    LETTER_DASH,
    LETTER_DOWN_AR,
    LETTER_DOWN_AR_NO,
    LETTER_DOWN_CROSS,
    LETTER_E,
    LETTER_ENE,
    LETTER_EXCLAM,
    LETTER_F,
    LETTER_FIRST_QUARTER,
    LETTER_FOURTH_QUARTER,
    LETTER_G,
    LETTER_H,
    LETTER_I,
    LETTER_J,
    LETTER_K,
    LETTER_L,
    LETTER_LEFT_AR,
    LETTER_LEFT_AR_NO,
    LETTER_LEFT_CROSS,
    LETTER_LEFT_RIGHT_LINE,
    LETTER_M,
    LETTER_N,
    LETTER_O,
    LETTER_P,
    LETTER_Q,
    LETTER_QUEST,
    LETTER_R,
    LETTER_RETURN_LEFT,
    LETTER_RETURN_RIGHT,
    LETTER_RIGHT_AR,
    LETTER_RIGHT_AR_NO,
    LETTER_RIGHT_CROSS,
    LETTER_RIVER,
    LETTER_S,
    LETTER_SECOND_QUARTER,
    LETTER_SZ,
    LETTER_T,
    LETTER_THIRD_QUARTER,
    LETTER_U,
    LETTER_UP_AR,
    LETTER_UP_AR_NO,
    LETTER_UP_CROSS,
    LETTER_V,
    LETTER_W,
    LETTER_X,
    LETTER_Y,
    LETTER_Z,
    LETTER_LAKE,
    LETTER_CYR_LAKE;

    @Override
    public String asString() {
        return this.name().toLowerCase(Locale.ROOT);
    }

    public static Letters findLetterByBlock(ItemStack inHand) {
        return Letters.valueOf(inHand.getItem().toString().toUpperCase(Locale.ROOT));
    }
}
